### ISSUE TITLE
Cookie error when downloading pre-2003 workshop

### ISSUE THREAD

**Issue by irefuse** [iamtheyammer/fetch-ford-service-manuals#18]
I'm getting an error very shortly after starting the command to download the files:

user@User-PC:~/fetch-ford-service-manuals$ yarn start -c templates/params.json -s templates/cookieString.txt -o ~/Manuals/2001F-150/
Processing cookies...
Creating a headless chromium instance...
Downloading pre-2003 workshop manual, please see README for details...
Downloading and processing alphabetical index...
Saving manual files...
Saving 1-2 Accumulator (IN-VEHICLE REPAIR, Automatic Transmission — 4R70W)...
Encountered an error downloading 1-2 Accumulator (IN-VEHICLE REPAIR, Automatic Transmission — 4R70W)
/home/user/fetch-ford-service-manuals/src/pre-2003/saveEntireAlphabeticalIndex.ts:32
      await browserPage.goto("https://www.fordservicecontent.com" + href, {
                        ^
page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.fordservicecontent.com/pubs/content/~WS11/~MUS~LEN/19/S1171B46.HTM
Call log:
  - navigating to "https://www.fordservicecontent.com/pubs/content/~WS11/~MUS~LEN/19/S1171B46.HTM", waiting until "load"

    at saveEntirePre2003AlphabeticalIndex (/home/user/fetch-ford-service-manuals/src/pre-2003/saveEntireAlphabeticalIndex.ts:32:25)
    at async pre2003Workshop (/home/user/fetch-ford-service-manuals/src/index.ts:195:3)
    at async run (/home/user/fetch-ford-service-manuals/src/index.ts:78:5) {
  name: 'Error'
}

**Comment by irefuse** [comment]
in addition, if i use the --ignoreSaveErrors parameter, it scrolls through several of the above errors then finally starts "saving" files but they are just pdf files with the attached "You don't have permission to access..." message

![image](https://github.com/iamtheyammer/fetch-ford-service-manuals/assets/2688319/59abbac4-27dc-42a2-8951-001c85605cb8)

**Comment by irefuse** [comment]
I was able to get the downloads for 2003+ (specifically a 2021 F-250) to work, however it errored out on the wiring diagram section and none of the images for the workshop manual came with the PDFs.


```
Saved workshop manual!
Saving wiring manual...
/home/josh/fetch-ford-service-manuals/.yarn/cache/axios-npm-0.26.0-ae9d5291c9-386cd8770c.zip/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^
Error: Request failed with status code 500
    at createError (/home/josh/fetch-ford-service-manuals/.yarn/cache/axios-npm-0.26.0-ae9d5291c9-386cd8770c.zip/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/josh/fetch-ford-service-manuals/.yarn/cache/axios-npm-0.26.0-ae9d5291c9-386cd8770c.zip/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/josh/fetch-ford-service-manuals/.yarn/cache/axios-npm-0.26.0-ae9d5291c9-386cd8770c.zip/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:531:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
```
![image](https://github.com/iamtheyammer/fetch-ford-service-manuals/assets/2688319/7b74ff6b-40d1-466c-97b3-41eecf80462d)

**Comment by iamtheyammer** [comment]
Sounds like a cookie issue. Double check them and try again— perhaps you’re missing some?

**Comment by irefuse** [comment]
i followed the instructions exactly and this is what's happening. you say "cookies" implying more than one? the documentation only specified pulling the 1 from TableofContent page (which is what i did). it's the one from the Request Headers section, right?

**Comment by iamtheyammer** [comment]
Perhaps you're using a VPN? For me to diagnose this further you'll have to email me your params.json and cookieString.txt files, ideally along with your PTS username and password.

**Comment by irefuse** [comment]
I'm not on a VPN, but I sent you an email with the files and info you were asking for. It's only a 72-hour subscription though, so I hope you get an opportunity to take a look.

**Comment by iamtheyammer** [comment]
Got your email, thanks for sending it over. Using your files, I was actually able to download both _workshop_ manuals and the 2002 F-150's wiring manual: I think you may have been blacklisted by Akamai (Ford's bot protection service), which often lasts a few hours. Give it another shot-- if it still doesn't work, perhaps try another internet connection.

As for the 2021 F-250's wiring manual, it's suffering from the wiring manual bug that was fixed in #17, but those changes haven't been merged into master and tested yet, should take me a few hours (now that I have a set of credentials I can test and merge it)!

**Comment by irefuse** [comment]
i tried the 2002 F-150 again after no having tried since Friday and it still failed with the same ERR_HTTP2_PROTOCOL_ERROR so im not sure what's going on there. tried it off of my phone's hotspot as well.. not sure what im doing wrong. 

i am also still getting the missing pictures on the 2021 manual. I sent you a request via another email. by the time i can try again tomorrow, the subscription will have expired unfortunately
